# Generated by Django 4.1.1 on 2022-10-16 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0003_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="notes",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
